apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-ms
  template:
    metadata:
      labels:
        app: example-ms
    spec:
      containers:
      - name: example-ms
        image: asgeorge123/node:latest
        ports:
        - containerPort: 8080
